Added ElevenLabsClass <No Mergeroni>
SunBear1/deepfake-detection pull request #7
Opened 2023-09-21 13:27 UTC by eska5

Added ElevenLabsAPI class
- `readTexts`   reads texts in chosen voice and saves to directory 
readFile takes txt file and messages there should be separated by ";" 🦖 
- adds new voice based on mp3 files can be more than 1️⃣ 
- deletes chosen voice
- list voices
- set voice
Added utils file to help with files operations
Added Mock scenario

NOT TESTED I AM MONEY BLOCKED 💵 💰 💳 

To be discussed:
- I didn't make indexing new files so it is TODO 😿

2023-09-29 05:33 UTC, SunBear1 reviewed
Powoli zbliżamy się do upragnionego celu bracie w Chrystusie ⛵

2023-09-29 05:33 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +@app.post("/create_voice/")
```suggestion
@app.post("/create_voice")
```
Dotyczy to wszystkich endpointów. Nie chcemy mieć / na koniec

2023-09-29 05:33 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +        return {"message": "Voice {payload.name} created successfully"}
```suggestion
        return Response(status_code=status.HTTP_201_CREATED, content="Voice {payload.name} created successfully")
```
Dotyczy wszystkich pozostałych. Nie mniej jednak nie wszędzie będzie 201

2023-09-29 05:33 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +async def set_voice(payload: SetVoicePayload):
Set voice nie powinien istnieć, bo jest niezgodny z crudem.

- Delete voice/{id}, kasujemy istniejące voice
- Create voice, tworzymy nowy voice
- Use voice/{id}, generujemy mp3 za pomocą już istniejącego głosu
- Get voice/{id}, pobieramy detale na temat konkretnego głosu
- Get voices, pobieramy wszystkie głosy

Set voice jest redundanty bo use voice używa go pod spodem.

2023-09-29 05:33 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +async def read_texts(payload: ReadTextsPayload):
to powinno się chyba właśnie nazywać `use_voice`

2023-09-30 08:12 UTC, SunBear1 requested changes
Nice work 🥳. Zaczyna to faktycznie mieć ręce i nogi. Dodatkowo przetestuj jak ta apka będzie działać wewnątrz kontenera dockerowego, czy wszystko jest git

2023-09-30 08:12 UTC, SunBear1 commented on .vscode/settings.json
> +{
Ten plik do gitignora

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +app = FastAPI()
```suggestion
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +        directory = os.getcwd() + os.sep + file.filename.split(".")[0]
Tak naprawdę to nie jest directory tylko ścieżka zapisu pliku. Proponuje "file_path"

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +            description=f"{file.filename}",
Czemu to jest w stringu?

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +@app.get("/get_voices")
Masło maślane
```suggestion
@app.get("/voices")
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +@app.post("/delete_voice/{voiceID}")
```suggestion
@app.delete("/voice/{voiceID}") 
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +@app.post("/use_voice/{voiceID}")
```suggestion
@app.put("/voice/{voiceID}")
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +async def use_voice(voiceID: str, text: str = Form(...)):
Musimy to przekazywać przez form? Może użyjemy tu basemodelu i payloadu

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +@app.post("/create_voice")
```suggestion
@app.post("/voices")
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsApi.py
> +            status_code=status.HTTP_200_OK,
```suggestion
            status_code=status.HTTP_204_NO_CONTENT,
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsLogic.py
> +    def readTexts(self, text, voice):
Nie ma typu :(

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsLogic.py
> +    def getVoice(self):
Myśle czy ta funkcja ma sens

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/elevenLabsLogic.py
> +    def setVoice(self, voice) -> None:
Myśle czy ta funkcja ma sens

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/engine.py
> +from azure_client import AzureStorageClient
Czemu tutaj przenosimy ten moduł?

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/events.py
> -from service.engine import Engine
Tutaj tak samo, czemu przenosimy ten plik w inne miejsce?

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/utils.py
> +def getMP3_from_dir(MP3directory):
Ta funkcja chyba działa dla wszystkich plików nie tylko MP3 więc może by ją uogólnić? Np. get_all_files_from_dir(directory_name: str)

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/utils.py
> +def fileTXT_to_list(filenameAndFilepath):
```suggestion
def file_content_to_list(file_path: str) -> List:
```

2023-09-30 08:12 UTC, SunBear1 commented on src/generator/endpoints/utils.py
> +    return mp3_files
```suggestion
    return mp3_files

```

2023-09-30 08:13 UTC, SunBear1 requested changes
Nice work 🥳. Zaczyna to faktycznie mieć ręce i nogi. Dodatkowo przetestuj jak ta apka będzie działać wewnątrz kontenera dockerowego, czy wszystko jest git

2023-09-30 10:29 UTC, eska5 commented on src/generator/endpoints/elevenLabsLogic.py
> +    def setVoice(self, voice) -> None:
już nie 💯 💰 🦕

2023-09-30 10:31 UTC, eska5 commented on src/generator/endpoints/elevenLabsApi.py
> +async def use_voice(voiceID: str, text: str = Form(...)):
W sumie to stwierdziłem że jakbym miał tylko dla tego użyć payload to w sumie wywaliłem import xD

2023-10-06 12:52 UTC, merged